#Listen 80
<VirtualHost *:80>
    ServerName localhost

    # Proxy hacia tu app principal Next.js
    ProxyPass "/wizard/" "http://localhost:3000/"
    ProxyPassReverse "/wizard/" "http://localhost:3000/"

    # Proxy hacia tu app secundaria
    ProxyPass "/ce/" "http://localhost:10240/"
    ProxyPassReverse "/ce/" "http://localhost:10240/"

    # Opcional: cabeceras y timeouts
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
    ProxyTimeout 300
</VirtualHost>
